services:
  mnemosyne:
    ports:
      - "8080:80"
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mnemosyne-mysql

  mnemosyne-mysql:
    command: --lower_case_table_names=1
    build:
      context: ./Database/